pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                script { withSonarQubeEnv( installationName: 'sq1') { // You can override the credential to be used
                        sh 'mvn sonar:sonar'
                        }
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        // stage('Deliver') {
        //     steps {
        //         sh './jenkins/scripts/deliver.sh'
        //     }
        // }
    }
}
